package qa.test.tl.model;

import java.io.Serializable;

import java.math.BigDecimal;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.eclipse.persistence.indirection.ValueHolderInterface;

/**
 *  ###  Generated by Oracle JDeveloper 11g Release 1 11.1.1.6.38.61.92 - Tue Jan 31 16:13:32 PST 2012.  ###
 */

public class Emp implements Serializable {

    /**Map deptno <-> qa.test.tl.model.Dept
     * @associates <{qa.test.tl.model.Dept}>
     */
    private ValueHolderInterface deptno;

    /**Map mgr <-> qa.test.tl.model.Emp
     * @associates <{qa.test.tl.model.Emp}>
     */
    private ValueHolderInterface mgr;

    /**Map empCollection <-> qa.test.tl.model.Emp
     * @associates <{qa.test.tl.model.Emp}>
     */
    private List<Emp> empCollection;
    private BigDecimal empno;
    private String ename;
    private String job;
    private Date hiredate;
    private BigDecimal sal;
    private BigDecimal comm;

    public Emp() {
        this.deptno = new org.eclipse.persistence.indirection.ValueHolder();
        this.mgr = new org.eclipse.persistence.indirection.ValueHolder();
        this.empCollection = new ArrayList();
    }

    public Emp(BigDecimal empno, String ename, String job, Date hiredate,
               BigDecimal sal, BigDecimal comm) {
        this.sal = sal;
        this.ename = ename;
        this.empno = empno;
        this.empCollection = new ArrayList();
        this.comm = comm;
        this.job = job;
        this.hiredate = hiredate;
        this.deptno = new org.eclipse.persistence.indirection.ValueHolder();
        this.mgr = new org.eclipse.persistence.indirection.ValueHolder();
    }

    public void addEmp(Emp anEmp) {
        this.empCollection.add(anEmp);
        anEmp.setMgr(this);
    }

    public void addEmp(int index, Emp anEmp) {
        this.empCollection.add(index, anEmp);
        anEmp.setMgr(this);
    }

    public BigDecimal getComm() {
        return this.comm;
    }

    public Dept getDeptno() {
        return (Dept)this.deptno.getValue();
    }

    protected ValueHolderInterface getDeptnoHolder() {
        return this.deptno;
    }

    public List<Emp> getEmpCollection() {
        return this.empCollection;
    }

    public BigDecimal getEmpno() {
        return this.empno;
    }

    public String getEname() {
        return this.ename;
    }

    public Date getHiredate() {
        return this.hiredate;
    }

    public String getJob() {
        return this.job;
    }

    public Emp getMgr() {
        return (Emp)this.mgr.getValue();
    }

    protected ValueHolderInterface getMgrHolder() {
        return this.mgr;
    }

    public BigDecimal getSal() {
        return this.sal;
    }

    public void removeEmp(Emp anEmp) {
        this.empCollection.remove(anEmp);
        anEmp.setMgr(null);
    }

    public void setComm(BigDecimal comm) {
        this.comm = comm;
    }

    public void setDeptno(Dept deptno) {
        this.deptno.setValue(deptno);
    }

    protected void setDeptnoHolder(ValueHolderInterface deptno) {
        this.deptno = deptno;
    }

    public void setEmpCollection(List<Emp> empCollection) {
        this.empCollection = empCollection;
    }

    public void setEmpno(BigDecimal empno) {
        this.empno = empno;
    }

    public void setEname(String ename) {
        this.ename = ename;
    }

    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public void setMgr(Emp mgr) {
        this.mgr.setValue(mgr);
    }

    protected void setMgrHolder(ValueHolderInterface mgr) {
        this.mgr = mgr;
    }

    public void setSal(BigDecimal sal) {
        this.sal = sal;
    }

}
